# Generated by Django 4.1.6 on 2023-02-10 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_demomodel_name_alter_demomodel_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demomodel',
            name='value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demomodel',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
